### ISSUE TITLE
Why maxsize is used even if both width and height are under it

### ISSUE THREAD

**Issue by hixus** [hanagejet/exif-rotate-js#112]
Why maxsize is used even if both width and height are under it? Would seem more intuative that it only clips larger images.

**Comment by hanagejet** [comment]
I think uploaded images have to be the same size. But I didn't think about your use case.
So I will fix this issue.

**Comment by hixus** [comment]
ok, cool. We are using this for preprocessing input image for react-easy-crop so it should keep original width/height. Otherwise the crop information outputted by react-easy-crop will be wrong. The original image with crop information is sent to backend which will handle exif adjustments.
