### ISSUE TITLE
Not working with Safari

### ISSUE THREAD

**Issue by ethanchiu10** [hanagejet/exif-rotate-js#163]
Rotation is wrong when using iOS13.4.1

**Comment by hanagejet** [comment]
@ethanchiu10 Where in the code is the problem?

**Comment by ethanchiu10** [comment]
Upon more testing, it seems Safari (both on iOS and Mac) handles EXIF data differently than other browsers. If you try the demo https://hanagejet.github.io/exif-rotate-js-playgournd/ in Safari, you will see that it is not working. 

You can read a bit more about this issue here: https://github.com/GoogleChromeLabs/squoosh/issues/299

**Comment by hanagejet** [comment]
I can't see problem in Safari (ver.13.0.4) with [this images](https://github.com/recurser/exif-orientation-examples):
![スクリーンショット 2020-04-23 15 14 30](https://user-images.githubusercontent.com/4067007/80065483-2a907700-8575-11ea-9694-239a153ba9f7.png)

Can I get problem picture??

**Comment by ethanchiu10** [comment]
I'm on Safari 13.1, and this is what I see using that same demo picture (Portrait_8).
![Screenshot 2020-04-23 at 1 20 16 PM](https://user-images.githubusercontent.com/6167769/80065943-34aa7980-8565-11ea-8765-ea6a2fea33ff.jpg)

**Comment by hanagejet** [comment]
Ah, Safari 13.1 is not working. Ok, I will fix later. Thanks nice feedback.

**Comment by ethanchiu10** [comment]
Thank you so much for your hard work!

**Comment by hanagejet** [comment]
@ethanchiu10 Please check update on playground🙏
https://hanagejet.github.io/exif-rotate-js-playgournd/
