### ISSUE TITLE
Image type option

### ISSUE THREAD

**Issue by michellocana** [hanagejet/exif-rotate-js#240]
Hey, cool lib, using it for a while and works great! :)
The only issue i found is when you want to fix the exif in a transparent image, `getBase64Strings` returns a jpeg data URL with black background.
Maybe we can add a `type` option to pass the wanted mime type, what do you think? Let me know if i can submit a PR with that feature.

**Comment by hanagejet** [comment]
@michellocana Nice idea. Could you send me you PR??

**Comment by michellocana** [comment]
sure!
