### ISSUE TITLE
Feature - Add ability to pass quality parameter

### ISSUE THREAD

**Issue by oobayly** [hanagejet/exif-rotate-js#380]
[`HTMLCanvasElement.toDataURL()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) provides the ability to specify encoder options for specifying the lossy compression quality. The `TOptions` interface could easily be extended to include this parameter.

~I'll put a PR together for this.~

I've put together a PR for this. I've opted to leave the default quality undefined, so that it uses the default behaviour of the browser's javascript engine (which I believe defaults to 0.92)

**Comment by hanagejet** [comment]
@oobayly Thank you. Please check link of (HTMLCanvasElement.toDataURL()). I can't access.

**Comment by oobayly** [comment]
> @oobayly Thank you. Please check link of (HTMLCanvasElement.toDataURL()). I can't access.

Done
