### ISSUE TITLE
getBase64Strings is truncating the octet-stream in Windows environments

### ISSUE THREAD

**Issue by fabriciobrito** [hanagejet/exif-rotate-js#457]
The call `const data = await getBase64Strings(files, {maxSize, type, quality}))` is creating a request the ends up being truncated when running on a Windows machine:
![image](https://user-images.githubusercontent.com/2176049/167016954-a795e42d-f13f-459f-8f86-52ed4426dec8.png)
![image](https://user-images.githubusercontent.com/2176049/167017268-180aee23-9d55-4849-b8d4-53b41a5d44fe.png)

This issue was reproduced both in Chrome and Firefox on Windows 10. Check the content truncated to 1MB:
![image](https://user-images.githubusercontent.com/2176049/167017720-de69163a-8220-4fc1-a3f3-0924c31f654a.png)

Both browsers work fine when running on MacOS. Using the same file:
![image](https://user-images.githubusercontent.com/2176049/167017442-4b877a46-6228-42d7-9056-8c38ee433e4b.png)

Use a large file to reproduce the issue.

**Comment by hanagejet** [comment]
@fabriciobrito Thanks feedback. Have you check with [`readAsDataURL()`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL) ??
If you have size problems using `readAsDataURL`, I think `exif-rotate-js` dose not have problem.

**Comment by fabriciobrito** [comment]
No issue when using `readAsDataURL` without the lib, as suggested.
The main issue was that Windows could not recognize the file type for HEIC files in a pre-validation phase in our code that converted the file to JPG. Once that was fixed, `exif-rotate-js` worked fine again.
Thx for your help!
