### ISSUE TITLE
Version 1.0.2 - Cannot resolve module

### ISSUE THREAD

**Issue by mtjn** [hanagejet/exif-rotate-js#61]
Importing `exif-rotate-js@1.0.2` causes a breaking error
`Module not found: Can't resolve 'exif-rotate-js/lib' in '/path/to/file/with/import`

Have tried imports as:
`import { getBase64Strings } from "exif-rotate-js/lib";`
`import { getBase64Strings } from "exif-rotate-js";`

All fail. This error does not occur on `exif-rotate-js@1.0.1`

Code sandbox example (emitting different error): https://codesandbox.io/embed/wizardly-night-df64t

Error emitted: 
`Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency exif-rotate-js@1.0.2: ENOENT: no such file or directory, scandir '/tmp/223538212/node_modules/exif-rotate-js/lib'`

I don't understand why the package.json `main` field specifies `lib/index.js`, as there is no lib folder or index file.. But this is unchanged since version 1.0.1, so not sure why it would now cause this error.

**Comment by hanagejet** [comment]
@mtjn Thanks. Please check again.

**Comment by mtjn** [comment]
Looks good! thanks
